version: "3.7"

services:
  worker:
    build: 
      dockerfile: Dockerfile.dev
      context: ./Worker
    restart: always
    volumes:
      - ./Worker/src:/home/node/app/src
      - ./Worker/nodemon.json:/home/node/app/nodemon.json
    expose:
      - "8080"
    ports:
      - "8080"
      - "9229"
    command: npm start
  api:
    build: 
      dockerfile: Dockerfile.dev
      context: ./Master
    volumes:
      - ./Master/src:/home/node/app/src
      - ./Master/nodemon.json:/home/node/app/nodemon.json
    expose:
      - "9090"
    ports:
      - "9090"
      - "9229"
    command: npm start
  Balancer:
    image: nginx:1.15.2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - worker
    ports:
      - "5000:5000"